from app.algorithm.m01 import m01_coregister_images
from app.algorithm.m02 import m02_create_quickview_animation
from app.algorithm.m03 import m03_extract_rois
from app.algorithm.m04 import m04_detect_displacement
from app.algorithm.m05 import m05_detect_changes_acd
from app.algorithm.m06 import m06_detect_changes_mad
from app.algorithm.m07 import m07_detect_ships
from app.algorithm.m08 import m08_detect_aircrafts
from app.algorithm.m09 import m09_detect_vehicles
from app.algorithm.m10 import m10_detect_building_changes 
from app.algorithm.m11 import m11_detect_container_changes
from app.algorithm.m12 import m12_estimate_sst
from app.algorithm.m13 import m13_detect_oil_spills

from app.algorithm.n01 import n01_detect_all_facilities
from app.algorithm.n02 import n02_synchronize_ais_time
from app.algorithm.n03 import n03_detect_ships_high_recall
from app.algorithm.n04 import n04_remove_known_facilities
from app.algorithm.n05 import n05_generate_statistics
from app.algorithm.n06 import n06_update_known_facilities
